### ISSUE TITLE
Add progress_bar argument to the keyATM_read() function

### ISSUE THREAD

**Issue by jaeyk** [keyATM/keyATM#139]
## Requested feature

It would be great if a progress bar (see [this example](https://github.com/r-lib/progress)) is added to track the running time of the `keyATM_read()` function. 

```r
# Example
keyATM_read(progress_bar = TRUE)
```

## Use case

A progress bar could help track the remaining time to run the `keyATM_read()` function.

## Additional context

I noticed that it took quite a while for the `keyATM_read()` function to parse a large document-term matrix object. I'm currently using `tictoc::tic()` and `toc()` to document the running time. It would be convenient, however, if `progress_bar` option can be provided as one of the arguments of the function.

**Comment by Shusei-E** [comment]
Hi @jaeyk, thanks for the feedback! 

How about this? https://github.com/keyATM/keyATM/tree/package_dev
You can try it with `devtools::install_github("keyATM/keyATM", ref = "package_dev")`. The default is `progress_bar = FALSE` to be consistent with older versions.

(Also, let me know if it is fine to add your name in [NEWS.md](https://github.com/keyATM/keyATM/blob/package_dev/NEWS.md))

**Comment by jaeyk** [comment]
Thanks @Shusei-E  for very prompt response. 

re1: The number of documents is 1,394,468 and the number of unique terms is 1,115,574. (I reduced the number of the terms substantially by setting the minimum frequency threshold higher.)

re2: Welcome to add my name in the update markdown file.

**Comment by Shusei-E** [comment]
@jaeyk Thanks for the reply.

It seems the corpus is too large for keyATM (also it depended on the length of the documents), as keyATM does not use any approximation methods. Have you tried `stm`?
I am not sure if there is any off-the-shelf R package that can handle more than 1 million documents (it's impressive!).

JFYI: I had a discussion on using a large-scale corpus with another user before: https://github.com/keyATM/keyATM/issues/139

**Comment by jaeyk** [comment]
@Shusei-E Thanks. I noticed it when I took a look at the source code. Again, much appreciated for your reply. Then, I will try keyATM to a subset of the text of my interest.

**Comment by Shusei-E** [comment]
Thanks again for trying our package and your great suggestion!!

**Comment by jaeyk** [comment]
@Shusei-E I really like trying it out as post-theorization of topic modes has bothered me for a long time. Thanks for co-developing this!
