### ISSUE TITLE
problem with dynamic topic modeling: free(): invalid next size (normal)

### ISSUE THREAD

**Issue by jaeyk** [keyATM/keyATM#141]
## Problem summary (required):
This is an example to show how to report a bug.

I can't run the dynamic topic modeling specified as follows: 
```r
dynamic_out_day <- keyATM(docs = keyATM_docs,    # text input
                      no_keyword_topics = 2,              # number of topics without keywords
                      keywords = keywords,       # keywords
                      model = "dynamic",         # select the model
                      model_settings = list(time_index = docvars(my_corpus)$index,
                                            num_states = 5),
                      options = list(seed = 250, store_theta = TRUE, thinning = 5))
```

I assume it has something to do with the C side of the package, but don't know exactly what's going on. My current hunch is the error might be related to the size of the data the function can handle.

## Environment information (required):
```r
sessionInfo()  # please run this in R and copy&paste the output

R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
 [1] quanteda_2.1.0  forcats_0.5.0   stringr_1.4.0  
 [4] dplyr_1.0.0     purrr_0.3.4     readr_1.3.1    
 [7] tidyr_1.1.0     tibble_3.0.2    ggplot2_3.3.2  
[10] tidyverse_1.3.0 here_0.1        keyATM_0.3.0   
```

## Actual output (required):

```r
# Please copy and paste the error message

R 
Initializing the model...
Fitting the model. 1500 iterations...
free(): invalid next size (normal)
Aborted (core dumped)

```

## Expected output (it helps us a lot):
Please explain what you expected to happen.

When I ran the dynamic model with the month index, it worked (**6 months**). When I extended the time index to days (**159 days**), the function stopped working. 

## A minimal reproducible example or a reprex (it helps us a lot):
Please paste minimal code that reproduces the bug. If possible, please upload the data file as `.rds`.

Unfortunately, I cannot share the data publicly.

**Comment by Shusei-E** [comment]
Thanks for posting this. Does the tutorial code run on your computer?
https://keyatm.github.io/keyATM/articles/pkgdown_files/keyATM_dynamic.html

**Comment by jaeyk** [comment]
@Shusei-E Yes, that one and my simpler dynamic topic model (6 months) both worked well.

**Comment by jaeyk** [comment]
@Shusei-E I will convert days into weeks and circle back to you. if the size of the data is the problem, then that trick might work. For your reference, `keyATM_docs` has 140,713 elements. Also, thanks for your helpful suggestion last time.

**Comment by Shusei-E** [comment]
Thanks for trying it. Then, I guess there would be an issue with the data input, as it seems the error raises before the fitting starts (not during the iteration).
(I cannot further check it only with the error output, sorry)

**Comment by jaeyk** [comment]
@Shusei-E No worries. Thanks for your extremely prompt reply. I will close this issue after confirming whether converting weeks into days works.

**Comment by Shusei-E** [comment]
Of course! 
How does your `docvars(my_corpus)$index` look like? It should have values `1, 2, 2, ...`.

**Comment by jaeyk** [comment]
Then var type is correct. I'm doing some various tests and can get back to you either tonight or early tomorrow.

**Comment by jaeyk** [comment]
@Shusei-E Following your advice, I rechecked the index variable and found that its format is not consistent with the required. I think that turning year into an index variable is a relatively easy problem then turning a date (e.g., YEAR-MONTH-DAY) variable into an index variable.

Here's how I fixed the problem. 

```r
# Time index  

# Convert date into integer 
index <- as.integer(gsub("-", "", docvars(my_corpus)$date))

# Replace elements

char_index <- as.character(index)

# Condition 
given <- sort(unique(index)) %>% as.character()

# For loop 
for (i in seq(1:length(unique(index)))){
  
    char_index[char_index == given[i]] = paste(i)

    message(paste("replaced", i))

}

# Check 
unique(char_index) %>% as.numeric() %>% sort()

# Arrange and assign 
docvars(my_corpus, "index") <- char_index %>% as.integer()

docvars(my_corpus) <- docvars(my_corpus) %>%
  arrange(index)
```

**Comment by Shusei-E** [comment]
Thanks for digging into this issue. Is it possible to share here a part of the time index that gave you an error (of course not the data part, just the index)? 

keyATM checks time index input, but I may need to update it. I originally thought it is fine if the package checks that the value increments by 1 (https://github.com/keyATM/keyATM/blob/v0.3.0/R/model.R#L695).

My general impression is that handling `date` data is tricky, as there are many ways to represent the same information (e.g. `2020-07-10` = `07-10-2020` = `07/10, 2020`), so I would like to leave the formatting to other packages, such as [lubridate](https://lubridate.tidyverse.org/). It should be useful to add more this point to the tutorial.

**Comment by jaeyk** [comment]
re2: This was the problem. As you can see first 8-9 elements looked fine, that's why I missed the issue. 

```r
 [1]  1  1  1  2  2  3  3  3  3  5  9
 [12]  9  9  9  9  9  9  9 10 10 12 12
 [23] 12 12 12 12 12 12 12 12 12 12 13
```

re1: Agreed that a package should do one job and one job well. (I loved the UNIX philosophy.) Then, you might want to add another error handling condition that can check whether the index var is consistent with the required format. 

I will close the issue and thank you as alwasy!

**Comment by Shusei-E** [comment]
This is really helpful, thanks as always!
