### ISSUE TITLE
document-topic distribution returns 0

### ISSUE THREAD

**Issue by YixiC94** [keyATM/keyATM#148]
## Problem summary (required):
I ran KeyATM on a collection of survey responses I have. Each response is short and the total number of tokens is around 30000. I set the number of topics = 5. Would the small-N be the reason why `out$theta` returns 0 after I run below code? 

```
out <- keyATM(docs = keyATM_ALL,       # text input of all 30000 tokens
              no_keyword_topics = 1,    # number of topics without keywords
              keywords = keywords,      # keywords
              model = "base",           # select the model
              options = list(seed = 250,
              store_theta = TRUE))
```

## Environment information (required):
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.5
```

## Actual output (required):
```
out$theta is empty
```

## Expected output (it helps us a lot):
I expect out$theta returns certain number, instead of being all 0

**Comment by Shusei-E** [comment]
Thanks for using our package!

Did you get the same error if you try [this example](https://keyatm.github.io/keyATM/articles/pkgdown_files/keyATM_base.html)?
On my computer, I got `out$theta` and couldn't replicate your issue.

![Screen Shot 2020-08-19 at 2 03 51](https://user-images.githubusercontent.com/16630777/90598064-55f03f00-e1c0-11ea-9b62-68734b952cbc.png)

If you pass your `out` object to `top_docs()`, what does it return?

**Comment by YixiC94** [comment]
Thanks Shusei! When I tried the example, it produced the result as desired. However, below is a screenshot when I tried to pass it on to my own dataset. Could this be a result of blank cells (NA) in my data frame? 
![Screen Shot 2020-08-19 at 8 52 51 AM](https://user-images.githubusercontent.com/56045752/90643741-81dbe680-e1f9-11ea-9ac6-98970e809c4c.png)

**Comment by Shusei-E** [comment]
Thanks for trying it!
So I suppose the screenshot is the output of `top_docs(out)`. This function uses the values of `theta` internally.
Could you tell me a bit more about your data -- what does `summary(keyATM_ALL)` return?

**Comment by YixiC94** [comment]
Sure! The summary function returns below result. 
```
keyATM_docs object of: 3 documents.
Length of documents:
  Avg: 13545
  Min: 1
  Max: 40632
   SD: 23458.03
Number of unique words: 2617
```
My data consists 5 columns of survey response (text) data (NA exist), and 2 columns with survey score (numeric data). I've processed the text data as dfm and converted into a keyATM readable format.

**Comment by Shusei-E** [comment]
Thank you! I wonder why there are only three documents. If it is a survey, I was expecting the number of respondents is several hundred. So the unit of analysis is not a respondent?

**Comment by YixiC94** [comment]
You are right! I double-checked and realized that I accidentally dropped majority of my documents during the preprocessing stage. The model is working perfectly now. Thanks for developing this wonderful package.

Best,
Yixi
________________________________

**Comment by Shusei-E** [comment]
Great to know it. Now I close this issue. Thanks again for using our package!
