### ISSUE TITLE
Option to keep .id or some other overt var to connect back to original df

### ISSUE THREAD

**Issue by debusklaneml** [keyATM/keyATM#155]
## Requested feature

It would be very useful to connect the outputted theta values to the original verbatims for modal classification purposes. Although currently you can grab theta from the keyATM_ouput object and can merge it back in to the original df, it is less than obvious and explicit.

## Use case

This would be used to examine the probability of topic assignment for each document. 

Thank you for a great package!

**Comment by Shusei-E** [comment]
Hi @debusklaneml, thanks for using our package and leaving the feedback.
When you say "original df," does it mean the original covariate matrix or the original document-term matrix?
(probably I can use doc_id for the theta's row names, is that what you need?)

**Comment by debusklaneml** [comment]
Yes, it would be amazing to have the doc_id for the theta row names. It seems that currently it is just simply numbered. If the doc_id was either as a column/field or as a rowname, users could merge it back to the original data frame that likely contains one line per document (pre tokenization df). I hope this helps. If not, I'm happy to generate repex for clarity. Cheers.

**Comment by Shusei-E** [comment]
Thanks for the clarification! Currently, the row order of `theta` is the same as the order of input documents, i.e., the first row of `theta` corresponds to the first document. (The exception is the case where the package needs to drop an empty document)
I agree that adding `doc_id` to the theta will make it clearer.

**Comment by debusklaneml** [comment]
Got it. 

My solution has been to use the quanteda 'convert' function to push the post-tokenized and post-empty dropped dfm back to a data frame to gather a list of rownames of docs that are actually used in the keyATM function. This is then, post keyATM output, cbinded back to the theta matrix (which I convert to a data.frame). Then I simply merge this data.frame back to the original dataset where each line is a document. This obviously leaves those that were dropped in preprocessing without any information... which is actually what I want, as those are often one word responses or not useful and removed for whatever reason during cleaning. I actually do a bit more during this process to subset the theta matrix down to identify which topic most well aligns to each doc_id (highest probability--modal topic assignment).

Would it be helpful to see this process in a repex?

**Comment by Shusei-E** [comment]
Yes, the repex will be helpful!

**Comment by debusklaneml** [comment]
This reprex follows the documented preparation and base examples. 

1. A data.frame was created from the example 'corpus' data to show a typical situation and one where the 'doc_id' is a column.
2. The final dfm is converted back to a data frame to capture the final list of 'doc_id's that are used in the keyATM analysis. 
3.  out$theta is converted to a df for manipulation and cbinded to the final list of 'doc_id's used in the analysis. 
4. The highest topic probability is captured for each 'doc_id' used in the analysis. 
5. This is then able to be merged back with the original df. 


``` r
# Reprex 

library(tidyverse)
library(keyATM)
#> keyATM 0.3.1 successfully loaded.
#>  Papers, examples, resources, and other materials are at
#>  https://keyatm.github.io/keyATM/
library(quanteda)
#> Package version: 2.1.2
#> Parallel computing: 2 of 8 threads used.
#> See https://quanteda.io for tutorials and examples.
#> 
#> Attaching package: 'quanteda'
#> The following object is masked from 'package:utils':
#> 
#>     View
library(reprex)

data(data_corpus_inaugural, package = "quanteda") # data import

# create data.frame to mimic typical situation
df <- as.data.frame(as.matrix(data_corpus_inaugural)) %>% 
  rownames_to_column(var = 'doc_id')

# these steps follow all preparation, keyword, and base
# information found here: https://keyatm.github.io/keyATM/articles/pkgdown_files/Preparation.html#preparing-keywords-1
data_tokens <- tokens(data_corpus_inaugural,
                      remove_numbers = TRUE,
                      remove_punct = TRUE,
                      remove_symbols = TRUE,
                      remove_separators = TRUE,
                      remove_url = TRUE) %>%
  tokens_tolower() %>%
  tokens_remove(c(stopwords("english"),
                  "may", "shall", "can",
                  "must", "upon", "with", "without")) %>%
  tokens_select(min_nchar = 3)

data_dfm <- dfm(data_tokens) %>%
  dfm_trim(min_termfreq = 5, min_docfreq = 2)

# convert final dfm after all triming (token removals & document removals) to 
# gather row names to match to keyATM 'out' later
dfm_rownames <- convert(data_dfm, to = c('data.frame')) %>% 
  select(doc_id)

keyATM_docs <- keyATM_read(texts = data_dfm)
#> Using quanteda dfm.
summary(keyATM_docs)
#> keyATM_docs object of: 58 documents.
#> Length of documents:
#>   Avg: 876.19
#>   Min: 48
#>   Max: 3001
#>    SD: 509.977
#> Number of unique words: 2568

keywords <- list(Government     = c("laws", "law", "executive"),
                 Congress       = c("congress", "party"),
                 Peace          = c("peace", "world", "freedom"),
                 Constitution   = c("constitution", "rights"),
                 ForeignAffairs = c("foreign", "war"))

out <- keyATM(docs              = keyATM_docs,    # text input
              no_keyword_topics = 5,              # number of topics without keywords
              keywords          = keywords,       # keywords
              model             = "base",         # select the model
              options           = list(seed = 250))
#> Initializing the model...
#> Fitting the model. 1500 iterations...
#> Creating an output object. It may take time...

# grab theta as data.frame
theta <- as.data.frame(out$theta)

# bind it back to rownames grabbed from final dfm
theta_rownames <- cbind(dfm_rownames, theta)

# by document highest theta topic probability (modal topic assignment)
modal_topic_assign <- theta_rownames %>% 
  pivot_longer(cols = !contains('doc_id')) %>% 
  group_by(doc_id) %>% 
  slice_max(value) %>% ungroup()

# merge modal topic assignment back to original df
back_to_original_df <- left_join(df, modal_topic_assign)
#> Joining, by = "doc_id"
```

Please let me know if you have any questions. Cheers.

**Comment by Shusei-E** [comment]
Thank you, this is really helpful. Right now we are working on the new version of the paper, but we will see how we can integrate your idea into the code.

**Comment by Shusei-E** [comment]
@debusklaneml Thanks again for your idea! I [added](https://github.com/keyATM/keyATM/pull/157/commits/138c121af7c52d554247c4bcd10b12aff2a625af) a `keep_docnames` option in the next version (not on CRAN yet but will be soon!)

```r
keyATM_docs <- keyATM_read(texts = data_dfm, keep_docnames = TRUE)

keywords <- list(Government     = c("laws", "law", "executive"),
                 Congress       = c("congress", "party"),
                 Peace          = c("peace", "world", "freedom"),
                 Constitution   = c("constitution", "rights"),
                 ForeignAffairs = c("foreign", "war"))

out <- keyATM(docs              = keyATM_docs,    # text input
              no_keyword_topics = 5,              # number of topics without keywords
              keywords          = keywords,       # keywords
              model             = "base",         # select the model
              options           = list(seed = 250, iterations = 5))

head(out$theta)
```

I didn't explicitly prepare a function to get the highest topic probability because I think the implementation is relatively straightforward once you have `theta` with document names.
```r
theta %>% 
  mutate(doc_id = row.names(.)) %>%
  pivot_longer(cols = !contains("doc_id")) %>% 
  group_by(doc_id) %>% 
  slice_max(value) %>% ungroup()
```

**Comment by debusklaneml** [comment]
Fantastic, thank you.
