### ISSUE TITLE
ProgressBar for keyATM

### ISSUE THREAD

**Issue by kweinert** [keyATM/keyATM#166]
## Progress Bar for keyATM

It would be nice to monitor the iterations of keyATM, for instance in shiny

```r
# Example
iter <- 1500
shiny::withProgress(message("Running keyATM", max=iter)
out <- keyATM::keyATM(docs=docs, no_keyword_topics=num_topics, keywords=keyw, model= "base", options=list(iterations=iter, pb=shiny::setProgress)) 
```

## Use case

I would like to use this great package from within Shiny.

**Comment by Shusei-E** [comment]
Hi @kweinert, thanks for the feedback! I've never used Shiny for my project--doesn't it show the default progress bar like this? (Can Shiny show the output from the package?)
![Screen Shot 2021-08-12 at 19 18 04](https://user-images.githubusercontent.com/16630777/129281978-f1833ac7-df1f-45ee-a9aa-dd0feb2bdedf.png)

**Comment by kweinert** [comment]
Good point, I will try and report back.

**Comment by Shusei-E** [comment]
keyATM uses `RcppProgress` in a C++ file to [show the progress bar](https://github.com/keyATM/keyATM/blob/master/src/keyATM_meta.cpp#L345), which might make things more complicated. 

We have a `verbose = TRUE` option. If there is a way to parse the output (it shows `1`, `10`, `20`, `30` etc), can these numbers be used to show a progress bar on the Shiny side?
```r
out <- keyATM(docs              = keyATM_docs,    # text input
              no_keyword_topics = 5,              # number of topics without keywords
              keywords          = keywords,       # keywords
              model             = "base",         # select the model
              options           = list(seed = 250, verbose = TRUE))
```
```
Fitting the model. 1500 iterations...
[1] log likelihood: -4.78492e+06 (perplexity: 8093.1)
[10] log likelihood: -4.17967e+06 (perplexity: 2592.85)
[20] log likelihood: -4.07092e+06 (perplexity: 2113.24)
[30] log likelihood: -4.0281e+06 (perplexity: 1949.76)
[40] log likelihood: -4.00472e+06 (perplexity: 1865.86)
[50] log likelihood: -3.98705e+06 (perplexity: 1804.91)
[60] log likelihood: -3.98182e+06 (perplexity: 1787.23)
[70] log likelihood: -3.97703e+06 (perplexity: 1771.18)
[80] log likelihood: -3.97225e+06 (perplexity: 1755.34)
[90] log likelihood: -3.96587e+06 (perplexity: 1734.4)
```

**Comment by kweinert** [comment]
Hi Shusei-E, 
verbose=TRUE would be fine if message would be used instead of cat/print. The reason for this is that we can define a callback handle for message/warning/error that works with shiny. With cat/print, we only have capture.output, which collects all output and returns it after all work is done.

**Comment by Shusei-E** [comment]
I see. So if keyATM uses [`Rcpp::message`](https://github.com/RcppCore/Rcpp/pull/1146) instead of [`Rcerr`](https://teuder.github.io/rcpp4everyone_en/060_utility.html) when `verbose = TRUE`, can Shiny handle it? Then I think [this part of the code](https://github.com/keyATM/keyATM/blob/master/src/keyATM_meta.cpp#L386) needs some changes.
Feel free to fork this repo and send us a pull request. I'm happy to review it and include you as [a contributor](https://github.com/keyATM/keyATM/blob/master/DESCRIPTION#L5).

**Comment by kweinert** [comment]
Hi. I tried to fork and use Rcpp::message. Problem is, I am not an C++ programmer and am not used to this toolset I use remotes::install_github to compile, which is slow and requires pushing for each try. I can not make sense from the compiler output. 

From https://github.com/RcppCore/Rcpp/issues/1145 I understand that there is a Rcpp::message function. But I do not understand if I need to include some header or convert the message to strings or ...

Is is conceivable for you that you do this adaption and I provide a working example on how to use keyATM from shiny?

Kind regards,
Karsten

**Comment by Shusei-E** [comment]
I made some minimum changes. Could you try `keyATM` in the `Shiny` branch? https://github.com/keyATM/keyATM/tree/Shiny
It uses `Rcpp::message()` when `verbose = TRUE`.

**Comment by kweinert** [comment]
Yes, this works perfectly! I did not know about the SEXP and wrap stuff... Thank you!

Here is an (almost) minimal app:

    library(keyATM)
	library(quanteda)
	library(shinydashboardPlus)
	data(keyATM_data_bills)
	bills_keywords <- keyATM_data_bills$keywords
	bills_dfm <- keyATM_data_bills$doc_dfm  
	keyATM_docs <- keyATM_read(bills_dfm)
	
	ui <- shinydashboardPlus::dashboardPage(
		header=shinydashboardPlus::dashboardHeader(),
		sidebar = shinydashboardPlus::dashboardSidebar(),

		body=shinydashboard::dashboardBody(
			shinydashboardPlus::box(
				status="primary", width=12,
				shiny::fluidRow(
					shiny::column(4,
						shiny::numericInput('num_topics', 'New Topics', 5, min=0, max=20)
					),
					shiny::column(4,
						shiny::numericInput('num_iter', 'Iterations', 300, min=150, max=5000)
					),
					shiny::column(4,
						shiny::actionButton("run_lda", "Run keyATM")
					)
				)
			),
			
			shinydashboardPlus::box(
				status="primary", width=12,
				shiny::plotOutput("result")
			)
		)
	)

	server <- function(input, output, session) {
		shiny::observeEvent(input$run_lda, {
			shiny::withProgress(
				withCallingHandlers(
					out <- keyATM(
						docs = keyATM_docs, 
						model = "base", 
						no_keyword_topics = input$num_topics, 
						keywords = bills_keywords,
						options=list(verbose=TRUE, iterations=input$num_iter)
					),
					message=function(m) if(grepl("^\\[[0-9]+\\]", m$message)) {
						val <- as.numeric(gsub("^\\[([0-9]+)\\].*$", "\\1", m$message))
						shiny::setProgress(value=val)
					}
				),
				message="fitting model..",
				max=input$num_iter,
				value=0
			)
			output$result <- shiny::renderPlot(keyATM::plot_modelfit(out))
		})
	}

 	app <- shiny::shinyApp(ui, server)
	shiny::runApp(app, launch.browser=TRUE)

Would be great if you could make this changes permanent. 

Kind regards from Berlin,
Karsten

**Comment by Shusei-E** [comment]
@kweinert Great to know it. The Shiny app looks cool! Yes, I will include this change in the new version https://github.com/keyATM/keyATM/pull/167 (not sure when to release it on CRAN, though).
