### ISSUE TITLE
Compatibility with LDA measures for model comparison?

### ISSUE THREAD

**Issue by amacanovic** [keyATM/keyATM#169]
## Requested feature

I really enjoyed working with this package - thank you for all the work on it!

What I do miss when working with keyATM is a feature that would enable a comparison among models with different number of topics based on several existing measures.

In particular, the package LDAtuning by @nikita-moor has been of immense help when working with LDA implementations (https://cran.r-project.org/web/packages/ldatuning/index.html).

I was wondering if any of those measures could be also used with keyATM?

I wanted to check whether some of the functions in LDAtuning could be "adjusted" to work with the keyATM base model.
However, since I do not understand all the nuances of how keyATM works compared to LDA models, I was not even sure if any of these adjustments would be valid. 

The measures calculated by the LDAtuning package rely on output of LDA models built with topicmodels. So, by reading through the keyATM documentation, I concluded the following:

I gathered that
```r
LDAmodel@logLiks
```
would be matched by the following for keyATM models:
```r
keyATMmodel$model_fit$`Log Likelihood`
```

Other metrics call for the beta probabilities of terms over topics:

```r
LDAmodel@beta
```

Reading the documentations of keyATM, I concluded this is comparable to phi?
```r
keyATMmodel$phi
```

And the posterior topic distributions:
```r
LDAmodel@gamma
```
would correspond to:
```r
keyATMmodel$theta
```

Would any of functions relying of the LDA model outputs above work with keyATM as well?

Thank you!

**Comment by Shusei-E** [comment]
Hi, Ana 
Thanks for the comment!

Yes, `Log Likelihood` is the log-likelihood, `phi` is the topic-word distribution and `theta` is the document-topic distribution. 
I suppose to make `ldatuning` package compatible with `keyATM`, the authors of `ldatuning` will need to edit their package.

(As you can see in Figure 4 of [our paper](https://arxiv.org/pdf/2004.05964.pdf), one of our claims is that you don't need to adjust the number of topics as long as you provide a reasonable set of keywords.)

**Comment by amacanovic** [comment]
Hi Shusei,

Thank you very much for your swift reply!

I indeed noticed that the results were quite stable in my application across the number of topics for topics which were initiated with keywords. Still, I was curious about exploring how other topics that did not build up on those seedwords vary with different numbers of topics specified.

As far as I am concerned, I do not necessarily need an update of the ldatuning package; as long as I know I am substituting the objects in the function correctly.

I will then close this topic!
