### ISSUE TITLE
Keyword selection algorithm

### ISSUE THREAD

**Issue by arodloff** [keyATM/keyATM#170]
Hey, 
I hope this is the right channel to address this question: 
In the preparation section on the keyATM website, you write: "Researchers can use other methods such as a keyword selection algorithm proposed in King, Lam and Roberts (2017)."

However, the keyAMT package does not seem to have a function for this algorithm.  Did I overlook something, or was this sentence meant to encourage the readers to make this implementation themselves?

Thanks in advance!

**Comment by tomoya-sasaki** [comment]
Hi @arodloff,

Thanks for reaching out and for your interest in our package! 
The keyATM package does not have the implementation of King, Lam, and Roberts' algorithm. We believe there are a variety of algorithms to select keywords and our intention is to share one example of them. The replication package of King, Lam, and Roberts contains the implementation [here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/FMJDCD&version=1.1). 

Tomoya
