### ISSUE TITLE
A heads-up: Change to dependency **matrixNormal**

### ISSUE THREAD

**Issue by phargarten2** [keyATM/keyATM#172]
With much thanks to [https://github.com/phargarten2/matrixNormal/issues/1](url), the Kronecker Product in `matrixNormal::rmatnorm` has been changed from `koch(U,V)` to `koch(V,U)`. The original version used a citation in a paper that was found to be incorrect. I have updated the package (submitting it to CRAN for approval). I am sorry for any inconvenience.

**Comment by Shusei-E** [comment]
Got it, thanks for the heads up!
