### ISSUE TITLE
Regex and Keywords

### ISSUE THREAD

**Issue by lfagliano** [keyATM/keyATM#173]
Hi authors!

Thank you a lot for this wonderful package, this is a great tool and it is helping me a lot with my research! I have a question/suggestion below, I am not a very experienced person on topic modelling but this is from my experience using the package so far. 

Currently, I am exploring the package through a research project I have on Twitter data. However, I am slightly confused over the use of keywords and whether the keywords option support dictionary which contains regex. For instance, when I select "Terror*" (aiming for terrorism/terrorist/terror), I can see that visualize_keywords() thinks that the words are not in the corpora when it actually is. Thus, I am led to believe that KeyATM does not support keywords with regex. 

Yet, this presents two problems, I think:
 1.  It complicates the use of keywords with lemmatized and stemmatized corpora, which from literature I have come to believe it is a gold standard in text analysis. That is because when I run the keywords on a lemmatized and stemmatized corpora, none of the keywords matches unless it is an exact match. 
 2. It requires us to come up with all the possible options for the keyword, which is also a problematic and not always reliable approach. 

Maybe could there be added the option of allowing the use of regex expressions for keywords? Or if that is not possible, it may be a good idea to add it to the documentation and ways around that as well if you have any recommendations, as I was looking for that but I couldn't find it. 

Hope this helps! Thanks again for the package!

**Comment by Shusei-E** [comment]
Hi @lfagliano, thanks for your feedback!

Re: regex  
As you wrote, `keyATM` does not support `regex` right now. The main reason is that we thought most users would preprocess documents, and they would set lemmatized/stemmatized terms as keywords (if we lemmatize/stemmatize corpus, we have to apply the same preprocessing to keywords).

Probably we can have a function that takes a regular expression and returns words that match in the corpus. In this way, you can use these words when you set keywords.
```r
> regex(corpus, "terror*")
terrorism terrorist terror
```

**Comment by lfagliano** [comment]
Hi @Shusei-E, thanks for your response. 

Yea, I think that would be a wonderful idea. 

I have just finished doing most of the work related to KeyATM and I wanted to thank you for the package, it is wonderful. Hopefully, I can get that published and reference your Artix working paper. 

Thanks!
