### ISSUE TITLE
change parallel::mclapply to future.apply::future_lapply in the initialization

### ISSUE THREAD

**Issue by grlju** [keyATM/keyATM#174]
## Comment

This is not a feature request, and it is also not a bug. 

In the initialization phase (line 394 of the model.R script) you use the `parallel::mclapply` function. This effectively prevents users from running the package in parallel on Windows machines. If you change this to `future.apply::future_lapply` Windows users would also be able to use the` parallel_init` option and it seems like you already use that function in the package. 

It seems like only a few lines of code would need to be changed and I could not discern if there was a particular reason for using `parallel::mclapply`. I would be happy to do this if required, but since it seems like such a minor thing, you may just want to do it (if you agree that it is a good change).

**Comment by Shusei-E** [comment]
Hi @grlju, it's a great point! I edited the code. Please try this branch: https://github.com/keyATM/keyATM/tree/package_v4

```r
# Installing from a branch
devtools::install_github("keyATM/keyATM", ref = "package_v4")
```
