### ISSUE TITLE
Error in mapped$set(keys[x], values[x]) : key must be not be "" or NA

### ISSUE THREAD

**Issue by rodtaq** [keyATM/keyATM#177]
Hello, thanks for your library. I made some tests and I have the same error (windows, R 3.6) 👍

Warning in check_keywords(info$wd_names, keywords, options$prune) :
Keywords will be pruned because they do not appear in documents: "interest_rates",
"net_margins", "cash_margins", [... truncated]
Error in mapped$set(keys[x], values[x]) : key must be not be "" or NA

Is there any restriction on how write the Keyword ?
Thk in advance

**Comment by tomoya-sasaki** [comment]
Hi @rodtaq, thank you for using our package! Could you share some reproducible examples as explained [here](https://keyatm.github.io/keyATM/)? It helps us understand your issue better. Thank you!

**Comment by Shusei-E** [comment]
@rodtaq Could you let us know how you set keywords? As Tomoya said, a reproducible example will be helpful. 
Please reopen this issue with the information so that we can dig in. Thanks!

**Comment by rodtaq** [comment]
Hi again , i edit the first post.
I removed the words that are NA in the visualize_keywords and it works.
Therefore few NA like "taxe" or others generate an error, maybe if the number of missing word is too important ?

**Comment by Shusei-E** [comment]
Hi @rodtaq, thanks for the update. Unfortunately, I couldn't replicate your example. Since we don't have your data, this is what we could do:

```r
library(keyATM)
library(quanteda)
library(magrittr)
data(data_corpus_inaugural, package = "quanteda")
data_corpus_inaugural <- head(data_corpus_inaugural, n = 58)

data_tokens <- tokens(data_corpus_inaugural,
                      remove_numbers = TRUE, 
                      remove_punct = TRUE, 
                      remove_symbols = TRUE,
                      remove_separators = TRUE,
                      remove_url = TRUE) %>%
                 tokens_tolower() %>%
                 tokens_remove(c(stopwords("english"), 
                               "may", "shall", "can",
                               "must", "upon", "with", "without")) %>%
                 tokens_select(min_nchar = 3)

data_dfm <- dfm(data_tokens) %>%
              dfm_trim(min_termfreq = 5, min_docfreq = 2)
keyATM_docs <- keyATM_read(texts = data_dfm)

keywords <- list(Government     = c("laws", "law", "executive"),
                 Constitution   = c("constitution", "rights"),
                 ForeignAffairs = c("foreign", "war", "missingword", "missing_word"))

visualize_keywords(docs = keyATM_docs, keywords = keywords)
```

This gives us:
```r
Warning in check_keywords(unique(unlisted), keywords, prune) :
  Keywords will be pruned because they do not appear in documents: missingword, missing_word
```
which looks fine to me.

Could you provide us with a **replicable** example and reopen this issue? We did our best but it was impossible for us to know what happened to your code without the example.

Thanks so much again for your patience and understanding.

**Comment by rodtaq** [comment]
Hi Shusei-E
Thanks for your reply, sorry I didn't see it ...
Well in your example just change the keywords list like this :

keywords <- list(Government     = c(**"pol", "pal", "pil"**),
                 Constitution   = c("constitution", "rights"),
                 ForeignAffairs = c("foreign", "war", "missingword", "missing_word"))

visualize_keywords(docs = keyATM_docs, keywords = keywords)

and you will obtain:
Warning in check_keywords(unique(unlisted), keywords, prune) :
  Keywords will be pruned because they do not appear in documents: pol, pal, pil, missingword, missing_word
**Error in check_keywords(unique(unlisted), keywords, prune) : 
  All keywords are pruned. Please check: Government**

Same I have if in any case you d'ont have any word in the topics I suppose

Hope this helps, regards
Rod
