### ISSUE TITLE
All keywords are pruned. Please chec

### ISSUE THREAD

**Issue by rodtaq** [keyATM/keyATM#179]
Hi Shusei-E
Thanks for your reply, sorry I didn't see it ...
Well in your example just change the keywords list like this :

keywords <- list(Government     = c(**"pol", "pal", "pil"**),
                 Constitution   = c("constitution", "rights"),
                 ForeignAffairs = c("foreign", "war", "missingword", "missing_word"))

visualize_keywords(docs = keyATM_docs, keywords = keywords)

and you will obtain:
Warning in check_keywords(unique(unlisted), keywords, prune) :
  Keywords will be pruned because they do not appear in documents: pol, pal, pil, missingword, missing_word
**Error in check_keywords(unique(unlisted), keywords, prune) : 
  All keywords are pruned. Please check: Government**

Same I have if in any case you d'ont have any word in the topics I suppose
I know in the doc it's written it xan happen, but I don't know why you didn't protect from this possibility: if any words match in the topic ?

Hope this helps, regards
Rod

_Originally posted by @rodtaq in https://github.com/keyATM/keyATM/issues/177#issuecomment-1085628984_

**Comment by Shusei-E** [comment]
Hi, thanks for the comment.
If all assigned keywords to a topic do not appear in the corpus, the topic is no longer the keyword-topic. Since `pol`, `pal` and `pil` are not in the corpus (please note that the keyATM only checks words in the document-feature matrix), it gave you an error.
I hope this helps. Thank you.

**Comment by rodtaq** [comment]
Hi again, thanks for your reply. Sorry I don't understand the logic, as it is not very useful to manage the error (as you don't know really by nature if all the words are in the topic or not). I don't know a good way how to manage the error but I will look.
Regards
