### ISSUE TITLE
by_strata_DocTopic() Credible Intervals 

### ISSUE THREAD

**Issue by pmeiners** [keyATM/keyATM#180]
Using keyATM 0.4.0

I am unable to change the credible interval inside the by_strata_DocTopic() function.
It works fine with the predict command, however changing the "ci" argument does not seem to influence the results.

Am I misunderstanding something?

**Comment by Shusei-E** [comment]
Hi @pmeiners, thanks for opening the issue! Is it possible to replicate the issue using [the example on the website](https://keyatm.github.io/keyATM/articles/pkgdown_files/keyATM_cov.html#covariates-and-document-topic-distributions)?

**Comment by Shusei-E** [comment]
Hi @pmeiners, it should be fixed in #181. Please install the package from GitHub and try it out. Feel free to reopen this issue if it doesn't work.

```r
devtools::install_github("keyATM/keyATM")
```

**Comment by pmeiners** [comment]
Thank you very much for the quick fix, and I am sorry for not providing an example.
Great package!
