### ISSUE TITLE
[Question] Extracting doc number/Checking perplexity of the output model

### ISSUE THREAD

**Issue by StrangeFate** [keyATM/keyATM#182]
Hi. 

First of all, thank you for making great package.
It has been really helpful for my arcademic research.

The thing that I'd like to ask about is extracting doc number with output model and checking final perplexity of the output model.
I have a news article data which is separated by news companies and I'd like to sort the docs out by a company with the topic number they have so that I can see the distribution of topics for the each news company.

What I have looked into so far is the function named "top_docs" with option "n".
I changed the "n" to print all the doc numbers belong exclusively to each topic but returned dataframe has duplicated doc number around the topics.
Will be there any way to extract the exclusive doc to topic number?
Also, please provide the way to check the perplexity of the output model.

Thank you.

**Comment by Shusei-E** [comment]
Hi, thanks for using our package!

Perplexity:
`values_fig(plot_modelfit(fitted_object))` should work.

Doc number:

>  all the doc numbers belong exclusively to each topic
`keyATM` considers a mixture of topics, so there is no document that exclusively belongs to a particular topic.

**Comment by StrangeFate** [comment]
Thank you for the reply!

I just ran the code for Perplexity and it worked really well.

Thank you again for making great package!
