### ISSUE TITLE
Clarify computation of weights_type = "inv-freq"

### ISSUE THREAD

**Issue by WenHanGao** [keyATM/keyATM#183]
In the configuration of `keyATM`, one of the parameter to be specified is `weights_type`. My understanding is that "information-theory" refers to -log base 2, which is presented in your paper. I would like to clarify how do you define the computation of inverse frequency. Thank you.

**Comment by tomoya-sasaki** [comment]
Thank you for using our package! The inverse frequency is based on the inverse term frequency, which is the inverse of the number of times a term appears in your corpus.

**Comment by WenHanGao** [comment]
Is there a way to use TFIDF in the implementation?

**Comment by Shusei-E** [comment]
Hi, @WenHanGao thanks for trying our package!
We didn't implement the TF-IDF version.

We construct weights [here](https://github.com/keyATM/keyATM/blob/c3232adaa47ea7bae1a9bd5cc582780060372c9f/src/keyATM_meta.cpp#L151). In theory, you can add an argument and use different weights.
