### ISSUE TITLE
Prediction of new documents for the base model

### ISSUE THREAD

**Issue by PanosP** [keyATM/keyATM#187]
## Requested feature
Hello, I haven't found a method to predict the topic of a new document with the Base model. If this is true, could you please provide this feature?

**Comment by tomoya-sasaki** [comment]
Thank you, @PanosP. Are you looking for a function like this in the `lda` package?
https://rdrr.io/cran/lda/src/R/predictive.distribution.R
https://rdrr.io/cran/lda/man/predictive.distribution.html

**Comment by PanosP** [comment]
Thanks for the quick response! I would like to use the good feature of the Base model being able to handle both known and unknown topics. I would like, for example, to use the Base model to predict if a new cybersecurity-related web document is related to a specific domain such as the naval industry (as the known topic, in contrast to every other possible domain).
For this purpose, I believe that a function like this [https://rdrr.io/cran/textmineR/man/predict.lda_topic_model.html] would be best, meaning that it would be useful to predict the topic of the new document as a whole (and not only of specific terms).

**Comment by Shusei-E** [comment]
Thanks. I can think of something like this:
```r
docs <- keyATM_read(docs_dfm)  # preprocessed corpus, a keyATM_doc object
docs_new <- keyATM_read(docs_dfm) # new documents

fit <- keyATM(docs, 5, keywords, model = "base")  # fitting the base model
pred <- predict_topicprop(fit, newdocs = docs_new)  # pred witll be a list of iter x (# of topics) matrices
```
We'll ask you to try a prototype once it's ready.

Do you think a new document contains a lot of words that do not appear in the corpus you'll use to train the base model?

**Comment by PanosP** [comment]
Yes, this sounds perfect! The new document is not expected to contain a lot of out of vocabulary words.
Thank you!

**Comment by Shusei-E** [comment]
Hi @PanosP, please check out this prototype.
[predict.R.zip](https://github.com/keyATM/keyATM/files/9488981/predict.R.zip)

**Comment by PanosP** [comment]
Hello. Running the code gave me the following error in the pred_topicprop() execution:
`pred_theta <- pred_topicprop(out, docs_predict)`

> Error in lapply(X = X, FUN = FUN, ...) : object 'alpha_est' not found

When executing the function pred_topicprop() line by line, it seems that the problem is in row 70 of the code:
`use_iter` <- max(fitted$values_iter$used_iter) * 0.7`
It gives the following error:

> Error in fitted$values_iter : object of type 'closure' is not subsettable

**Comment by Shusei-E** [comment]
Hi, thanks for trying it. I fixed a bug, and this version works fine on my laptop.

[predict.R.zip](https://github.com/keyATM/keyATM/files/9496519/predict.R.zip)

**Comment by PanosP** [comment]
Hello @Shusei-E . In my dataset, where (some of) the documents have out of vocabulary terms, the above code fails to execute with the following error:

> Error in pred_theta[[docid]][iter, ] <- table(z_d)/doclen[docid] : 
  number of items to replace is not a multiple of replacement length

I suspect that this is due to the out of vocabulary terms and the resulting difference in the lengths of the items of the docs_predict list in comparison to the lengths of the items in w_pred (but I am not sure).

**Comment by Shusei-E** [comment]
Hi @PanosP, thanks for trying it again. 

* Did my code with the example data in the package work on your computer?
* Could you provide me with a minimum replicable example? I didn't encounter the error you posted, and it's almost impossible to pin down a cause without an example. I need to replicate your error first. (please email me if it's better)

**Comment by Shusei-E** [comment]
A new prototype: [predict.R.zip](https://github.com/keyATM/keyATM/files/9594037/predict.R.zip)

**Comment by PanosP** [comment]
Thank you very much! I confirm that this also works in my computer.

**Comment by Shusei-E** [comment]
Great to know it!
