### ISSUE TITLE
Export iteration number to .txt file

### ISSUE THREAD

**Issue by domjoeval** [keyATM/keyATM#198]
## Requested feature

Hi folks, I'm wondering if you could add an option to export the iteration number to a .txt file while the model is converging.

## Use case

I'm currently working on a project that must be completed on a virtual machine through Jupyter Notebooks. Basically, I'm analyzing newspapers on ProQuest, and they require all analysis to be done through their VM. However, there is a lot of data and the interface is very poor and doesn't show the progress bar while the code is running. I could get around this issue if the `keyATM` function could export the iteration number to a .txt file. I completely understand if this use case is too specific to justify editing the main function in the package.

**Comment by Shusei-E** [comment]
Hi @domjoeval, check out the [`temp_txtout`](https://github.com/keyATM/keyATM/tree/temp_txtout) branch!
```
devtools::install_github("keyATM/keyATM", ref = "temp_txtout") 
```

This makes a text file named `keyATM_iter.txt` in your working folder ([code](https://github.com/keyATM/keyATM/blob/temp_txtout/src/keyATM_meta.cpp#L364)). This might be a very specific usecase and I won't put it in the CRAN version but I'll keep the branch until you finish your project!

**Comment by domjoeval** [comment]
Thank you so much Shusei! You're the best!

**Comment by Shusei-E** [comment]
I will close this issue for now, but please feel free to reopen it. I've never used R on Jupyter Notebooks and I'm not exactly sure it works.
