### ISSUE TITLE
keyATM plots do not show Chinese characters 

### ISSUE THREAD

**Issue by chentitus** [keyATM/keyATM#201]
Hi I am new to keyATM, and the text I am trying to analyze is Chinese. I found that plots generated by keyATM do not show Chinese characters, as shown below. Do I miss some steps? Any help is appreciated.

<img width="737" alt="Screenshot 2023-03-04 at 4 41 06 PM" src="https://user-images.githubusercontent.com/125351296/222886049-5eb27bae-e5c7-4229-bab7-3a9219748e91.png">

**Comment by Shusei-E** [comment]
Hi, thanks for reporting this. Could you answer some of the questions in the issue template, particularly the following:
```
## Environment information (required):
* Your OS
* R version
* keyATM version
```

If you save the plot as a PDF ([this way](https://keyatm.github.io/keyATM/reference/save_fig.html) or [this way](https://ggplot2.tidyverse.org/reference/ggsave.html)), can you see characters?

**Comment by tomoya-sasaki** [comment]
Hi @chentitus 
This thread might be helpful.
https://github.com/keyATM/keyATM/issues/189

**Comment by chentitus** [comment]
> Hi, thanks for reporting this. Could you answer some of the questions in the issue template, particularly the following:
> 
> ```
> ## Environment information (required):
> * Your OS
> * R version
> * keyATM version
> ```
> 
> If you save the plot as a PDF ([this way](https://keyatm.github.io/keyATM/reference/save_fig.html) or [this way](https://ggplot2.tidyverse.org/reference/ggsave.html)), can you see characters?

My OS: macOS Vantura 13.2.1 (22D68)
R version: 4.2.1 (2022-06-23)
keyATM version: 0.4.2

Unfortunately, neither way of saving the plot shows Chinese characters.

**Comment by chentitus** [comment]
> Hi @chentitus
> This thread might be helpful.
> #189

I followed instructions in the #189  thread to reinstall keyATM, but Chinese characters still do not show (see below). I think #189 deals with Windows system while my OS is Mac Vantura 13.2.1.

**Comment by Shusei-E** [comment]
OK, if you're using macOS, how about this?

```r
key_viz <- visualize_keywords(docs = keyATM_docs, keywords = keywords)
save_fig("keywords.pdf", key_viz, family = "Japan1GothicBBB")
```
You might need to change `Japan1GothicBBB` to a Chinese font (I don't know exactly, but `SimHei`?).

**Comment by chentitus** [comment]
> OK, if you're using macOS, how about this?
> 
> ```r
> key_viz <- visualize_keywords(docs = keyATM_docs, keywords = keywords)
> save_fig("keywords.pdf", key_viz, family = "Japan1GothicBBB")
> ```
> 
> You might need to change `Japan1GothicBBB` to a Chinese font (I don't know exactly, but `SimHei`?).

I tried three Chinese font types that I often used, but no luck... See below.

> save_fig("key_viz.pdf", key_viz, family="Kaiti TC")
Error in UseMethod("save_fig") : 
  no applicable method for 'save_fig' applied to an object of class "character"
> save_fig("key_viz.pdf", key_viz, family="SimHei")
Error in UseMethod("save_fig") : 
  no applicable method for 'save_fig' applied to an object of class "character"
> save_fig(key_viz, filename = "key_viz.pdf", family="SimHei")
Saving 8.38 x 6.01 in image
Error in grDevices::pdf(file = filename, ..., version = version) : 
  unknown family 'SimHei'
> save_fig(key_viz, filename = "key_viz.pdf", family="STKaiti")
Saving 8.38 x 6.01 in image
Error in grDevices::pdf(file = filename, ..., version = version) : 
  unknown family 'STKaiti'
> save_fig(key_viz, filename = "key_viz.pdf", family="Kaiti TC")
Saving 8.38 x 6.01 in image
Error in grDevices::pdf(file = filename, ..., version = version) : 
  unknown family 'Kaiti TC'

**Comment by Shusei-E** [comment]
Thanks for trying it (and sorry I made a typo in my code snippet). I think this is a ggplot2 issue but [this Stackoverflow post](https://stackoverflow.com/questions/55702377/ggplot2-doesnt-show-chinese-character-properly-in-rstudio-server-in-docker) seems to be related.

```r
library(showtext)
showtext_auto()
key_viz  # can you display the figure with the help of the `showtext` package?
save_fig(key_viz, filename = "key_viz.pdf", family="wqy-microhei")
```

**Comment by chentitus** [comment]
> Thanks for trying it (and sorry I made a typo in my code snippet). I think this is a ggplot2 issue but [this Stackoverflow post](https://stackoverflow.com/questions/55702377/ggplot2-doesnt-show-chinese-character-properly-in-rstudio-server-in-docker) seems to be related.
> 
> ```r
> library(showtext)
> showtext_auto()
> key_viz  # can you display the figure with the help of the `showtext` package?
> save_fig(key_viz, filename = "key_viz.pdf", family="wqy-microhei")
> ```

It worked! So it's a ggplot2 issue. You make my day! See the screenshot below.

<img width="1680" alt="Screenshot 2023-03-06 at 11 14 27 PM" src="https://user-images.githubusercontent.com/125351296/223151178-679a553c-54cc-4817-b596-dbdcfcabab33.png">

**Comment by Shusei-E** [comment]
Great to know it! Thanks again for using our package! I will close this issue.
