### ISSUE TITLE
A time_index problem

### ISSUE THREAD

**Issue by chentitus** [keyATM/keyATM#202]
Hi I am new to keyATM, and I am learning keyATM Dynamic. My data are Chinese newspaper articles, and there are 3-5 news reports per day (see the screenshot below please). I followed instructions on your website to prepare time index, but got the following error message: 
Error in check_arg_model_settings(obj, model, info) : `model_settings$time_index` does not increment by 1. 

How do I fix this issue? Any help is appreciated!

<img width="210" alt="Screenshot 2023-03-04 at 4 54 18 PM" src="https://user-images.githubusercontent.com/125351296/222886635-d1dfba73-a9af-4134-ad40-52bb7a0eeb1e.png">

**Comment by Shusei-E** [comment]
Hi, thanks for the issue. Can you show me how you specify the `keyATM()` function when you fit the model? Documents should be ordered by time and the time index should increment by 1. For example, `1 1 2 2 3 3` is fine but `1 1 2 4 4` and `1 1 2 1 3` are not acceptable inputs.

**Comment by chentitus** [comment]
> Hi, thanks for the issue. Can you show me how you specify the `keyATM()` function when you fit the model? Documents should be ordered by time and the time index should increment by 1. For example, `1 1 2 2 3 3` is fine but `1 1 2 4 4` and `1 1 2 1 3` are not acceptable inputs.

Thanks much for the info. I realized that there are missing dates in my data, which prevent time index from being incremental. I have just fixed it.
