### ISSUE TITLE
Changing the transition matrix

### ISSUE THREAD

**Issue by WenHanGao** [keyATM/keyATM#207]
I have a use-case of using the dynamic keyATM model. My transition matrix $P$ is restricted to a 2x2 matrix.
However, I would need the transition matrix to allow backward state switching. That is $P_{21}$ is non-zero.
I am thinking of changing the sampling procedure for $P$. 
Do you think it is possible? Hope you can offer some advice on where are the lines in the source code that I should be aware of.
Thank you.

**Comment by Shusei-E** [comment]
Hi @WenHanGao, thanks for the post.

> $P_{21}$ is non-zero

Unfortunately, the Chib (1998) paper we followed (cited in [p.22 of our paper](https://arxiv.org/pdf/2004.05964.pdf)) only allows for a one-step forward transition. If you wish, you can edit [this cpp file](https://github.com/keyATM/keyATM/blob/master/src/keyATM_HMM.cpp), but I suppose you need to employ a different HMM model. Particularly, you need to edit `initialize_specific()()`, `resume_initialize_specific()`, `sample_forward()`, `sample_backward()`, `sample_P()`, and `loglik_total()`.
