### ISSUE TITLE
Conditional posterior of alpha

### ISSUE THREAD

**Issue by WenHanGao** [keyATM/keyATM#209]
https://github.com/keyATM/keyATM/blob/ac78d1fd563acc9e0800e5b1342a2bb5374b0ea9/src/keyATM_base.cpp#L157C7-L157C7

Can I check why is this line inside the loop?
It seems to me that this should only be done once outside the loop when referring to the log of the conditional posterior distribution.
Or is there something I am missing?

**Comment by Shusei-E** [comment]
It's a direct implementation of [the equation S5](https://arxiv.org/pdf/2004.05964.pdf) but I think we can also take the term out of the \prod^{D}. The idea was I wasn't sure if we use \alpha_k or \alpha_{dk} (changing alpha by document) but in the end, we used \alpha_k for all documents.
