### ISSUE TITLE
"Saving the Model" gives wrong instructions

### ISSUE THREAD

**Issue by AMindToThink** [keyATM/keyATM#214]
## Problem summary (required):
The [preparation document](https://keyatm.github.io/keyATM/articles/pkgdown_files/keyATM_base.html) says to run these lines:
save(out, file = "SAVENAME.rds")
out <- readRDS(file = "SAVENAME.rds")

However, that doesn't work because R has separate functions for loading and reading RDS files. You can use save and load or saveRDS and loadRDS, but you can't mix them together. This is my first time coding in R, and it took me a while to figure out that problem. 
## Environment information (required):
```
sessionInfo()  # please run this in R and copy&paste the output
R version 4.3.3 (2024-02-29)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.4.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Chicago
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.3
```

## Actual output (required):
```
Error in readRDS(file = file_name) : unknown input format
Execution halted
```

## Expected output (it helps us a lot):
The rds file to be loaded back into the program from file.

**Comment by Shusei-E** [comment]
Hi @AMindToThink, thanks for opening the issue! 
The package internally uses [saveRDS](https://github.com/keyATM/keyATM/blob/5e994703f9abc641b712fddd18205544919aa9db/R/posterior.R#L600). However, it appears that save is not a generic function like print or summary. Let me find time to fix this.

**Comment by AMindToThink** [comment]
Thanks for looking into it. save worked without error and produced a file
with the rds extension. readRDS errors. I hope this helps.

**Comment by Shusei-E** [comment]
Hi @AMindToThink 
I decided to remove the internally defined `save()`. So you can use either `saveRDS()` or `save()`. I will also change the website instructions. 
You can try the new version from `devtools::install_github("keyATM/keyATM", ref = "v0.5.2")`. I will submit this new version to CRAN later today. Let me know if you have any other issues!

**Comment by Shusei-E** [comment]
Solved in https://github.com/keyATM/keyATM/pull/215
