### ISSUE TITLE
Question regarding `eta_1` vs. `eta_1_regular` (hyperparameter for topic-document distribution)

### ISSUE THREAD

**Issue by schae211** [keyATM/keyATM#216]
Maybe I misunderstood something, but I am somewhat confused by the following:

Given the following definition for  $\widetilde{\eta}_1$ `eta_1` and $\eta_1$ `eta_1_regular`

```math
\alpha_{k} \stackrel{\text { indep. }}{\sim} \begin{cases}\text{Gamma}\left(\tilde{\eta}_{1}, \tilde{\eta}_{2}\right) & \text { for } k=1,2, \ldots, \widetilde{K} \\ \text{Gamma}\left(\eta_{1}, \eta_{2}\right) & \text { for } k=\widetilde{K}+1, \widetilde{K}+2, \ldots, K\end{cases}
```

I was wondering why you set the shape parameters $`\tilde{\eta}_{1}=1`$ and  $`\eta_{1}=2`$. In particular why $\eta_1 > \tilde{\eta}_{1}=1$ which means we a priori give a larger probability to non-keyword topics. 

(see https://github.com/keyATM/keyATM/blob/022d7e40f274585f89f0f3e042ec66b8261aef6c/R/model.R#L799-L810) 

since the expected value of the Gamma distribution is `shape * scale` or `shape / rate`, i.e. here $\eta_1 * \eta_2$ or $\widetilde{\eta}_1 * \widetilde{\eta}_2$.

Also my understanding of `eta_1, eta_1_regular` is based on how these parameters are used here: https://github.com/keyATM/keyATM/blob/022d7e40f274585f89f0f3e042ec66b8261aef6c/src/keyATM_base.cpp#L150-L154 

and the corresponding function definition: https://github.com/keyATM/keyATM/blob/022d7e40f274585f89f0f3e042ec66b8261aef6c/src/keyATM_meta.cpp#L534-L538

**Comment by tomoya-sasaki** [comment]
Thank you for your question. You can change hyperparameter values with the `priors` option as described here: https://keyatm.github.io/keyATM/articles/pkgdown_files/Options.html
The default option assumes that there is quite a large proportion of non-keyword topics in the corpus but it might not be true in some cases and users are welcome to change hyperparameters.

**Comment by schae211** [comment]
okay, thanks a lot for the clarification!
