### ISSUE TITLE
Question regarding the document-topic distribution conditioned on covariates

### ISSUE THREAD

**Issue by schae211** [keyATM/keyATM#217]
- To illustrate my question, I ran the covariateModel as described in https://keyatm.github.io/keyATM/articles/pkgdown_files/keyATM_cov.html based on preparing the data as described in https://keyatm.github.io/keyATM/articles/pkgdown_files/Preparation.html

- I am somewhat confused by the description in https://keyatm.github.io/keyATM/articles/pkgdown_files/keyATM_cov.html#covariates-and-document-topic-distributions

- In the function `by_strata_DocTopic` you basically make predictions assuming a certain set of covariates for every document (aka sample). But I don't get why you do it that they. For reference see the apply_predict loop in https://github.com/keyATM/keyATM/blob/022d7e40f274585f89f0f3e042ec66b8261aef6c/R/analysis_covariates.R#L94-L140

- Why don't you just get coefficient corresponding the conditions of interest and run some computation based on the lambdas that habe been sampled during the Gibbs sampling (i.e. to get the conditional posterior distribution), e.g. something like (I can also copy and paste the pre-processing code which I took from the tutorials if that makes things easier/faster to run). 

```R
covariates_names <- colnames(out$kept_values$model_settings$covariates_data_use)

burn_in <- floor(max(out$model_fit$Iteration) / 2)
used_iter <- out$values_iter$used_iter
used_iter <- used_iter[used_iter > burn_in]
use_index <- which(out$values_iter$used_iter %in% used_iter)
tnames <- rownames(out$phi)

# in the covariate model, we sample those lambda parameters
lambda_iter <- out$kept_values$stored_values$Lambda_iter

df_theta_posterior <- purrr::imap_dfr(
  list("Republican_20_21c"=c(1, 1, 0, 1),
       "Democratic_20_21c"=c(1, 0, 1, 1),
       "Other_20_21c"=c(1, 0, 0, 1)),
  function(covar_vec, cond) {
    names(covar_vec) <- covariates_names
    covar_vec <- t(as.matrix(covar_vec))
    purrr::map_dfr(use_index, function(iter) {
      lambda = lambda_iter[[iter]]
      alpha_iter = exp((lambda %*% t(covar_vec))[,1])
      dirichlet_expect_iter = alpha_iter / sum(alpha_iter)
      tibble::tibble(condition=cond, 
                     topics=tnames,
                     alpha=alpha_iter,
                     dirichlet_expect=dirichlet_expect_iter,
                     iter=iter)
    })
  })

df_theta_posterior %>%
  ggplot() +
  ggridges::geom_density_ridges(aes(x=dirichlet_expect, y=topics, fill=condition), 
                                alpha=0.5, rel_min_height = 0.005) +
  scale_x_log10() +
  labs(x=expression(paste("Expected Value Dirichlet(", theta, "|", x, ")")),
       y="Topic")
```
- The results look very similar to the results shown in the tutoral/vignette.

**Comment by Shusei-E** [comment]
Hi Philipp, thanks for opening this issue with the details.

> Why don't you just get coefficient corresponding the conditions of interest and run some computation based on the lambdas that habe been sampled during the Gibbs sampling

Let's say we have L covariates. We are interested in the l-th covariate, and we want to marginalize out the (L-1) covariates. The intuition I had is that we want to respect the distribution of the (L-1) covariates.

We're using the sampled lambdas from Gibbs sampling.
https://github.com/keyATM/keyATM/blob/022d7e40f274585f89f0f3e042ec66b8261aef6c/R/predict.R#L98-L115

Does this answer your question? Feel free to ask a follow-up question!

**Comment by schae211** [comment]
Thanks for replying so quickly. Also thanks for developing such a useful model, and writing this nice package!

I do have one follow-up question, why do you require that `newdata` has the same number of rows as `data_used ` (the data used to get the posterior samples)?

https://github.com/keyATM/keyATM/blob/022d7e40f274585f89f0f3e042ec66b8261aef6c/R/predict.R#L33-L35

**Comment by Shusei-E** [comment]
> why do you require that newdata has the same number of rows as data_used (the data used to get the posterior samples)? 
> In my example, I think it would be nice if I could do something like this (or is that wrong for some reason?)

Hi! When I wrote the package, I wasn't really considering the use case you have in your example. I was thinking of using the `predict()` function for all documents in the corpus.

It seems you want to use the `predict()` function for a specific combination of covariates. For that purpose, your code snippet makes sense to me.

**Comment by schae211** [comment]
Okay thanks a lot!

There is one more thing in this context which confuses me.

What exactly is the difference between equations S15/S16 and S17 in arxiv version of keyATM. To paraphrase we have:

- Using $\boldsymbol{\lambda}$, we wish to obtain a posterior predictive distribution of $\theta_{d}$ given a new covariate data set $`\boldsymbol{X}=\boldsymbol{x}_{d}^{*}`$. The posterior predictive distribution is,

```math
p\left(\theta_{d}^{*} \mid \mathbf{x}_{d}^{*}, \mathbf{w}\right)=\int p\left(\theta_{d}^{*} \mid \mathbf{x}_{d}^{*}, \boldsymbol{\lambda}\right) p\left(\boldsymbol{\lambda} \mid \mu, \sigma^{2}, \mathbf{w}\right) d \boldsymbol{\lambda} \tag{S15}
```

- We can compute the posterior predictive distribution of the mean of $`\theta_{d}^{*}$ given $\mathbf{x}_{d}^{*}`$

```math
\mathbb{E}_{\boldsymbol{\lambda} \sim p\left(\boldsymbol{\lambda} \mid \mu, \sigma^{2}, \mathbf{w}\right)} \left[ \frac{\exp \left(\lambda_{k}^{\top} \mathbf{x}_{d}^{*}\right)}{\sum_{k^{\prime}=1}^{K} \exp \left(\lambda_{k^{\prime}}^{\top} \mathbf{x}_{d}^{*}\right)} \right] = \int \frac{\exp \left(\lambda_{k}^{\top} \mathbf{x}_{d}^{*}\right)}{\sum_{k^{\prime}=1}^{K} \exp \left(\lambda_{k^{\prime}}^{\top} \mathbf{x}_{d}^{*}\right)} p\left(\boldsymbol{\lambda} \mid \mu, \sigma^{2}, \mathbf{w}\right) d \boldsymbol{\lambda} \tag{S16}
```

- In contrast, to obtain the marginal posterior mean of $\theta_{dk}$ we use
```math
\begin{aligned}
\mathbb{E}\left[  \theta_{d k} \mid \mathbf{x}_{d}, \mathbf{w}\right]
&= \mathbb{E} \left[ \mathbb{E}\left[\theta_{d k} \mid \alpha_{k}, \boldsymbol{z}, \mathbf{w}\right] \rvert\, \mathbf{x}_{d}, \mathbf{w} \right] \\
&= 
\mathbb{E}\left[ \left. \frac{\exp \left(\boldsymbol{\lambda}_{k}^{\top} \mathbf{x}_{d}\right)+n_{d k}}{\sum_{k^{\prime}=1}^{K} \exp \left(\boldsymbol{\lambda}_{k^{\prime}}^{\top} \mathbf{x}_{d}\right)+n_{d k^{\prime}}} \right \rvert\, \mathbf{x}_{d}, \mathbf{w} \right] 
\end{aligned} \tag{S17}
```

**Comment by Shusei-E** [comment]
> What exactly is the difference between equations S15/S16 and S17 in arxiv version of keyATM

Eq.(S17) corresponds to the Eq.(9) on page 9. In (S15), we're using the distribution of \lambda (integrating over \lambda), but in (S17), we're using a single draw of lambda.

Implementation wise, (S15) and (S16) correspond to your original question where we use the stored lambdas from the iterations.

(S17) uses the lamda from [the last iteration](https://github.com/keyATM/keyATM/blob/master/R/posterior.R#L207). If the MCMC converges, using the last draw should be fine practically, and it will speed up the code because we don't need to look at all iterations.

**Comment by schae211** [comment]
> If the MCMC converges, using the last draw should be fine practically,

I don't quite get this statement. If MCMC converges, then the last sample is sampled from our target distribution (from the posterior), but how can we use one sample from posterior to estimate the mean? Doesn't that result in a very large variance?

**Comment by Shusei-E** [comment]
We use the last draw of lambda to calculate the \alpha_k in Eq.(9) for the covariate case. [In this post](https://stats.stackexchange.com/a/44495), we know the \alpha_1 from the covariates and lambda, and then x_1 is the n_{dk} in Eq. (9).

[The paper that proposed Collapsed Gibbs Sampling](https://www.pnas.org/doi/epdf/10.1073/pnas.0307752101) uses a single sample as well (p.5232, "We used a single sample taken after 2,000 iterations of Gibbs sampling...").

When we need the credible interval, the package uses sampled lambdas from the MCMC chain.

**Comment by schae211** [comment]
But one difference to the paper by Grifﬁths & Steyvers is that in their case $\alpha$ is a hyperparameter ("constant") while in keyATM it is a random variable.

**Comment by schae211** [comment]
> Are you suggesting that we should calculate theta using the sampled Z and lambda for each draw in Eq.(9)?

- I am not an expert in this, so I don't want to suggest anything.

- But what I don't understand is how it can be justified to only use the samples from the last MCMC iteration. Is there some theoretical justification for this?

- Also, how expensive would it be to compute for each thinning MCMC iteration (every 5 or 10) theta based on the sampled Z? (given that storing Z for each (thinning) iteration is way way to expensive).

**Comment by Shusei-E** [comment]
You can use the store_theta, but it can be memory intensive because we need to store the table of D x K for each iteration.

In the context of topic modeling, my understanding is that canonical papers like Griffiths et al. use the last draw because if the MCMC chain is long enough, you're sampling from the correct posterior distribution.

**Comment by schae211** [comment]
Thanks for taking the time to discuss this! I will close this issue for now.

**Comment by Shusei-E** [comment]
Of course! I hope it helped. Feel free to reopen this or open a new issue if you have any other questions!
