### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by gguangy** [keyATM/keyATM#219]
install.packages("keyATM")
Warning in install.packages :
  package ‘keyATM’ is not available (for R version 3.6.1)
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/bin/windows/contrib/3.6:
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/PACKAGES'
>

**Comment by tomoya-sasaki** [comment]
Hi, thanks for sharing your issue. As noted in DESCRIPTION, the package requires R version 4.0 or higher (`Depends: R (>= 4.0)`). Can you update your R version and try again? Thank you!

**Comment by Shusei-E** [comment]
I'm closing the issue for now. Please reopen the issue if using R>=4.0 doesn't work!
