### ISSUE TITLE
Explanation of table symbols

### ISSUE THREAD

**Issue by soubhikbarari** [keyATM/keyATM#27]
For full clarity, it'd be great if you guys could explain what the symbols in this table on the site mean!

<img width="682" alt="Screen Shot 2020-01-02 at 2 03 39 PM" src="https://user-images.githubusercontent.com/5015674/71686352-f5afa880-2d68-11ea-9b81-c546049ccbca.png">

Cheers!

**Comment by Shusei-E** [comment]
Thanks! Yeah, it is unclear. We added explanations!
https://github.com/keyATM/keyATM/pull/36
