### ISSUE TITLE
Dealing with large in-RAM data

### ISSUE THREAD

**Issue by contefranz** [keyATM/keyATM#97]
I am repeatedly running into a complete "R session aborted" in RStudio while attempting at running the model. I have a fairly large `dfm` with ~80k documents and 50k features. I am expecting this sample to grow in both N and P. 

Did you experienced any issue with large matrices?

**Comment by Shusei-E** [comment]
Hi, thanks for opening the issue! It seems `dfm` is too large. Have you tried trimming words with `quanteda`? (I usually preprocess to have 3k~5k features).

In our paper, the maximum number of documents is 17000. If you subset the data, does it run?

Also, could you follow [Bug report template](https://github.com/keyATM/keyATM/blob/master/.github/ISSUE_TEMPLATE/BugReport.md) and share the code with us?

**Comment by contefranz** [comment]
I can share a code which you could not run since I can't share the data. But you can replicate the issue by augmenting whatever `dfm` you have as example to reach 100k docs. 

To reply to your questions, yes, I can trim the `dfm` but I incur in other issues which I'll be happy to share in another bug-report (spoiler: when documents are empty).

I am issuing this bug since I did not have any issues with **topicmodels** and the function `LDA()`. Most of the analyses I do, and the community as well, deal with large corpora. 17k docs sound like a small corpus. 

My question then becomes: could you confirm that your code has issues in managing large in-RAM data? 

Sorry for this, I am just trying to see if your algorithm is approachable for big-data problems. If not, I need to turn to something else. 

Thanks

**Comment by Shusei-E** [comment]
### Code
Yes, I only need your code, not the data. I just want to know which function raises an error.

### Empty document
Removing empty document can be a part of preprocessing. We will include the point in the vignette we're writing! Thanks. 
```
data_dfm <- dfm_subset(data_dfm, ntoken(data_dfm) > 0)
```
Also, I think the package [checks the length of documents](https://github.com/keyATM/keyATM/blob/master/R/model.R#L90). Doesn't it raise an error? 

### Scalability
> 17k docs sound like a small corpus

When we started this project (almost four years ago!), that was enough (at least in PolSci). Now we have a sense with a small corpus, we have a plan to make it scalable.

> My question then becomes: could you confirm that your code has issues in managing large in-RAM data?

Yes, there should be a more efficient way to manage the data, which we need the community's help. We had to make several decisions to keep speed (we have more parameters), sacrificing the memory.

**Comment by contefranz** [comment]
# Problem
Actually, the problem is that I don't even see any error raising. The whole R session crashes which implies that I am struggling with finding the issues.

> Also, I think the package checks the length of documents. Doesn't it raise an error?
Yes, it raises an error. This is a different behavior w.r.t. `LDA()` in **topicmodels** which indeed drops the empty documents silently. I indeed use the same method you suggested to overcome the problem. Unfortunately, this reduces the size of `dfm` along `N` and so after the analysis, one has a corpus with `N` documents and a `dfm` with `N-n` documents where `n` are the empty documents. I don't think I like this approach though. I suggest you open up another thread and discuss this there.

# Size of objects
The original corpus, which will be larger in the future, has 88,642 documents and around 80k features (when converted into a `dfm`). The example below works on a sample of 1000 documents which lead to the following two `dfm`s: 

This is the toy `dfm`:
```r
> test_dfm
Document-feature matrix of: 1,000 documents, 33,323 features (97.0% sparse) and 11 docvars.
                  features
docs               risk factors carefully consider risks described uncertainties encompass affect company
  1029023_20060307    4      14         1        1    22         3             4         1      7       3
  1211583_20130401    9      12         1        0     7         0             0         0     11      10
  85974_20120229      5       7         0        0     4         0             2         0      8      56
  1679426_20170331    1       1         0        0     0         0             0         0      0       2
  1376307_20070330    1       1         0        0     0         0             0         0      0       0
  110027_20130308     1       1         0        0     1         1             0         0      0       4
[ reached max_ndoc ... 994 more documents, reached max_nfeat ... 33,313 more features ]
```

This is the trimmed toy `dfm`:

```r
> test_dfm_trimmed
Document-feature matrix of: 1,000 documents, 31,660 features (98.8% sparse) and 11 docvars.
                  features
docs               carefully encompass actually commercial-scale gtl ctl syntroleum constructed built licensees
  1029023_20060307         1         1        1                8  62  58         48           2     4        19
  1211583_20130401         1         0        0                0   0   0          0           0     0         0
  85974_20120229           0         0        0                0   0   0          0           0     3         0
  1679426_20170331         0         0        0                0   0   0          0           0     0         0
  1376307_20070330         0         0        0                0   0   0          0           0     0         0
  110027_20130308          0         0        0                0   0   0          0           0     0         0
[ reached max_ndoc ... 994 more documents, reached max_nfeat ... 31,650 more features ]
```

# Code

```{r}
set.seed( 1970 )
mycorp = corpus_sample( correct_corpus, 1000)
docvars( mycorp, "N_types" ) = ntype(mycorp)
test_dfm = dfm( mycorp, tolower = TRUE,
                remove = stopwords(),
                remove_punct = TRUE,
                remove_numbers = TRUE,
                remove_symbols = TRUE,
                remove_url = TRUE )
test_dfm = dfm_remove( test_dfm, 
                       "\\d+", 
                       valuetype = "regex" )
test_dfm = dfm_remove( test_dfm, 
                       "[^ -~]", 
                       valuetype = "regex" )
test_dfm = dfm_remove( test_dfm, 
                       "\\b\\w{1}\\b", 
                       valuetype = "regex" )
test_dfm = dfm_remove( test_dfm, 
                       "\\b\\w{2}\\b", 
                       valuetype = "regex" )
test_dfm_trimmed = dfm_trim( test_dfm,
                             min_termfreq = .05,
                             max_termfreq = .95,
                             termfreq_type = "quantile")

docvars( test_dfm_trimmed, "N_types_dfm" ) = ntype( test_dfm_trimmed )
test_dfm_trimmed = dfm_subset( test_dfm_trimmed, N_types_dfm > 0 )

keyATM_docs <- keyATM_read(test_dfm_trimmed)

# defining keywords
tax_keywords <- list(
  Risk = c("assessment", "apportion", "deductible", "nondeductible",
           "DTA", "DTL", "effective tax", "foreign tax", "haven", 
           "income,shift","indefinitely", "reinvested", "jurisdiction",
           "permanently", "reinvested","PRE","pretax","rate difference",
           "repatriate", "settle", "statutory", "tax basis"," tax credit",
           "tax expense", "taxable income", "tax law", "tax plan", "tax position",
           "tax provision", "tax strategy", "transfer pric", "trapped cash",
           "uncertain tax", "undistributed", "foreign", "earnings",
           "unrecognized", "tax benefit", "UTB", "valuation allowance"),
  Accounting = c("property", "properties", "capital", "operations", "notes",
                 "profitability", "equipment")
)
dt_vars = setDT(docvars(test_dfm_trimmed))
dt_vars[ , time_index := year - min( year ) + 1 ]
N_states = uniqueN(dt_vars$time_index)
out = keyATM( docs = keyATM_docs, 
              model = "dynamic", 
              model_settings = list( time_index = dt_vars$time_index,
                                     num_states = N_states ),
              keywords = tax_keywords,
              no_keyword_topics = 2,
              options = list( seed = 1970 ) )
```

**Comment by contefranz** [comment]
> Yes, as you pointed out, it should be a memory issue. So the RStudio crashes when you run keyATM(), right? Not keyATM_read()

Yes, it's when I try to run the model not reading the docs. 

So far, **topicmodels** does not use **Rcpp** directly, but uses the standard `.Call()` to invoke C++ code. You can find the code by inspecting the original function `LDA_VEM.fit()` [here](https://github.com/cran/topicmodels/blob/master/R/lda.R). 

This is my R session. My Mac has 16 GB of RAM.

``` r
sessionInfo()
#> R version 3.6.3 (2020-02-29)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS Catalina 10.15.4
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.6.3  magrittr_1.5    tools_3.6.3     htmltools_0.4.0
#>  [5] yaml_2.2.1      Rcpp_1.0.4      stringi_1.4.6   rmarkdown_2.1  
#>  [9] highr_0.8       knitr_1.28      stringr_1.4.0   xfun_0.12      
#> [13] digest_0.6.25   rlang_0.4.5     evaluate_0.14
```

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Shusei-E** [comment]
Thanks!

Yeah I was wondering authors of `topicmodels` add some manual memory protections.
I was looking at `Gibbs` code, as it is more closely related to `keyATM` than `VEM`.

**Comment by Shusei-E** [comment]
I tried three cases with more than 100k documents and 10k terms. 
* D = 100000, V = 10000
* D = 120000, V = 80000
* D = 150000, V = 100000
All of them ran properly.

The only error I had was related to creating a sparse matrix (which I believe the same as the quanteda’s dfm).

Of course, this is not a full replication of what you tried and multiple factors can make a difference. For example, I ran the code on Terminal rather than R studio, I use Mac OS Mojave rather than Catalina, and I tried the base model.

Let me close this issue for now.

```r
rm(list=ls()) ; gc()
library(keyATM)

rdirichlet <- function(n, alpha) {
  # From MCMCpack
  l <- length(alpha)
  x <- matrix(rgamma(l*n,alpha), ncol=l, byrow=TRUE)
  sm <- x %*% rep(1,l)
  return(x / as.vector(sm))
}

# Settings
D <- 150000
V <- 100000
K <- 10
alpha <- rep(50/K, K)
beta <- rep(0.1, V)

# Make a simulation data
thetas <- rdirichlet(100, alpha)  # 100 types of thetas
phi <- rdirichlet(K, beta)

doc_len_all <- rpois(D, lambda = 500)

# This runs out of memory when creating a data
# W <- parallel::mclapply(1:D,
#                         function(d) {
#                           doc_len <- doc_len_all[d]
#                           Z <- as.vector(rmultinom(1, size = doc_len, prob = thetas[sample(100, 1), ]))
#                           x <- rowSums(sapply(1:K, function(k) {rmultinom(1, size = Z[k], prob = phi[k, ])}))
#                         }, mc.cores = 5L)
# print("W Created")
# mat <- dplyr::bind_cols(W)
# rm(W) ; rm(thetas) ; gc()
# dfm <- Matrix::Matrix(as.matrix(mat))  # Error: vector memory exhausted (limit reached?)
# dfm <- t(dfm)
# dfm <- as(dfm, "dgCMatrix")
# colnames(dfm) <- paste0("W", 1:V)
# keyATM_docs <- keyATM_read(dfm)

vocab <- paste0("W", 1:V)
keyATM_docs <- parallel::mclapply(1:D,
                        function(d) {
                          doc_len <- doc_len_all[d]
                          Z <- as.vector(rmultinom(1, size = doc_len, prob = thetas[sample(100, 1), ]))
                          x <- rowSums(sapply(1:K, function(k) {rmultinom(1, size = Z[k], prob = phi[k, ])}))
                          y <- rep(vocab, x)
                          rm(Z); rm(x)
                          return(y)
                        }, mc.cores = 5L)
class(keyATM_docs) <- c("keyATM_docs", "list")
print("W Created")
rm(thetas) ; gc()

keywords <- list(Key1 = c("W10", "W20"), Key2 = c("W50", "W60"))

# Fitting
out <- keyATM(docs = keyATM_docs,
              no_keyword_topics = 8,
              keywords = keywords,
              model = "base",
              options = list(seed = 250, iterations = 20, parallel_init = TRUE))

print("Done")
```

```r
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin18.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS/LAPACK: /usr/local/Cellar/openblas/0.3.6_1/lib/libopenblasp-r0.3.6.dylib

locale:
[1] en_US/UTF-8/en_US/C/en_US/en_US

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Matrix_1.2-18  keyATM_0.2.0   nvimcom_0.9-83

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4       lattice_0.20-38  assertthat_0.2.1 dplyr_0.8.4     
 [5] crayon_1.3.4     grid_3.6.1       R6_2.4.1         lifecycle_0.2.0 
 [9] gtable_0.3.0     magrittr_1.5     scales_1.1.0     ggplot2_3.3.0   
[13] pillar_1.4.3     rlang_0.4.5      vctrs_0.2.4      ellipsis_0.3.0  
[17] tools_3.6.1      glue_1.3.2       purrr_0.3.3      munsell_0.5.0   
[21] compiler_3.6.1   pkgconfig_2.0.3  colorspace_1.4-1 tidyselect_1.0.0
[25] tibble_3.0.1   
```
