### ISSUE TITLE
Dropping empty documents silently

### ISSUE THREAD

**Issue by Shusei-E** [keyATM/keyATM#98]
`keyATM_read()` raises an error if there is an empty document. Should it drop the document silently? 

My position is that researchers should be explicit about all the modifications to the data. The number of documents that researchers think they use should match with the number actually used.

@tomoya-sasaki?

**Comment by tomoya-sasaki** [comment]
I thought through the same thing when I was talking with my cohorts, who had the same issue. 

> researchers should be explicit about all the modifications to the data. The number of documents that researchers think they use should match with the number actually used

I fully agree with this but maybe raising a warning would work as well. We also need to think about dropping corresponding covariates and timestamps if we do so.

**Comment by kosukeimai** [comment]
Let the model run with a specific warning.

**Comment by Shusei-E** [comment]
@kosukeimai We can implement it as an option `drop`.

@tomoya-sasaki We can probably store the document index as a part of `keyATM_doc` object, although it breaks backward compatibility.

**Comment by Shusei-E** [comment]
I updated the code: #99 
@contefranz Thanks again. I put your name in `NEWS.md` for your helpful suggestion. Let me know if you feel uncomfortable with it.

**Comment by contefranz** [comment]
@Shusei-E No problem with that. Thanks for asking.
